export let GET_USER_PENDING = "GET_USER_PENDING"
export let GET_USER_SUCCESS = "GET_USER_SUCCESS"
export let GET_USER_ERROR = "GET_USER_ERROR"


export let POST_USER_PENDING = "POST_USER_PENDING"
export let POST_USER_SUCCESS = "POST_USER_SUCCESS"
export let POST_USER_ERROR = "POST_USER_ERROR"


export let DELET_USER_PENDING = "DELET_USER_PENDING"
export let DELET_USER_SUCCESS = "DELET_USER_SUCCESS"
export let DELET_USER_ERROR = "DELET_USER_ERROR"